### ISSUE TITLE
Nuke install directory errors

### ISSUE THREAD

**Issue by javiertoledovis** [SpaghettiBaguette/hqueue-renderScript#4]
Hello.

I'm having an issue with your script. Everything goes fine (Server connection successful, file found and the job reaches Hqueue). The thing is that all jobs fail and the log says "'C:\Program is not recognized as an internal or external command,"
We are using the default install directory and it looks like the space in Program Files is causing trouble.

Any ideas on how to solve this?

Thank you, this script looks great =)

**Comment by JoshkVFX** [comment]
Should be able to put a \ before the space to prevent that error
I'll take a look tonight

**Comment by JoshkVFX** [comment]
Yeah it looks like adding the backslash before the space prevents that error. WIll look into improving that in future versions.

**Comment by javiertoledovis** [comment]
Thank you, I'll give it a try on Monday.

Cheers!
